### ISSUE TITLE
Ptv service line breaks

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/kunta-api-management#11]
Embedded Ptv service compontent line breaks are not working correctly

**Comment by jerelauha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) PTV tiedossa vielä rivitysongelma, ks. https://mikkeli.kunta-api.fi/sisalto/palvelut/opetus-ja-koulutus/oppilaanohjaus](https://trello.com/c/aVKA5gy0/34-1-ptv-tiedossa-viela-rivitysongelma-ks-https-mikkeli-kunta-api-fi-sisalto-palvelut-opetus-ja-koulutus-oppilaanohjaus)

**Comment by anttileppa** [comment]
Related issue: https://github.com/Metatavu/wordpress-kunta-api-services/issues/12
